### PR TITLE
Util/vector_emplace_back.hpp: Utility function to wrap around missing operations in `std::vector<bool>`.

### LINKED ISSUE #14: Error building on FreeBSD
On FreeBSD 11.3-RELEASE-p11 I downloaded v0.4 and then:

    pkg install libev

(version 4.33 got installed).

Output of `./configure` is [here](https://gist.github.com/hosiawak/6af50fb40bd04d61a6ad7205c173efb6)

[1st error](https://gist.github.com/hosiawak/5afb0c910733fcc70dc2c262bdec1501) after running `gmake`.

Renaming `std::site_t` to `__site_t` in Bitcoin/hash160.hpp fixes this problem

[2nd error](https://gist.github.com/hosiawak/111e5eb0d2d701c0af0ac19d92762515)

Unfortunately I have no idea how to fix this. I'm happy to try whatever you suggest and report back.

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #14 

@hosiawak can you check?

### CODE REVIEW

**Comment by hosiawak** [comment]
OK, I downloaded the zip file of this branch but there's no `configure` so running `autoreconf -i` gives me [this error.](https://gist.github.com/hosiawak/43578de1c662269a4cccc92775dc43e4)

**Comment by ZmnSCPxj** [comment]
The error arises from `libsecp256k1` build system, lemme see what I can do to poke it.  Cannot replicate on my system.  For now, try this tarball that has a `configure`: [clboss-vector-bool-emplace.tar.gz](https://github.com/ZmnSCPxj/clboss/files/5498138/clboss-vector-bool-emplace.tar.gz)

**Comment by hosiawak** [comment]
Running `./configure` results in [this error](https://gist.github.com/hosiawak/88a183b36522ba1b18a88b614a087690) on FreeBSD (it's fine on OS X).

Running `./configure --disable-dependency-tracking` finishes sucessfully on FreeBSD.

Building using `gmake` on FreeBSD is [closer but no cigar](https://gist.github.com/hosiawak/70852c2552d031aae9a020554c850a38).

Building on Mac OS results in [different errors](https://gist.github.com/hosiawak/14e43d591878c613458857ef30607c50) earlier in the build process.

We can focus on FreeBSD first since that's what's running on the servers.

**Comment by ZmnSCPxj** [comment]
Thanks, I will merge this in then and file a new issue for `plus`.

**Pull request merged**
