### PR TITLE
release-v0.13rc2

### PR DESCRIPTION
**Pull request by ksedgwic**
- Renamed and updated CHANGELOG.md

Addresses #172

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
looks like that the build system take in consideration also the logs

```
configure.ac:7: installing 'auxdir/missing'
Makefile.am: error: required file './ChangeLog' not found
Makefile.am: installing './INSTALL'
Makefile.am: installing 'auxdir/depcomp'
parallel-tests: installing 'auxdir/test-driver'
autoreconf: error: automake failed with exit status: 1
```

We can try to make a modification to it! I will try to take a look in the coming days

**Comment by ksedgwic** [comment]
Apologies for not catching that.  I think we should change the name of the file back to what autotools expects.  I think we should stick with the "Keep a Changelog" format though.

**Review by vincenzopalazzo — APPROVED** [review]
>Apologies for not catching that. I think we should change the name of the file back to what autotools expects. I think we should stick with the "Keep a Changelog" format though.

I agree.

ACK https://github.com/ZmnSCPxj/clboss/pull/174/commits/b065cc35f37138b382537bbaeb91fd51cee80b93

We are ready for this rc2

**Comment by ksedgwic** [comment]
Ok, we should be tagged

**Pull request merged**
