### PR TITLE
Add `balance` unmanagement key

### LINKED ISSUE #108: Switch to disable rebalancer/initial rebalancer
Is it possible to either introduce a switch that disables all rebalancers globally, or at least the initialrebalancer?
Or clboss-unmanage have a "rebalance" switch that does disable all rebalances for a channel?

Rationale: Initial rebalancer is doing serious damage here, from multiple point of views:
- currently i have to disable clboss alltogether if i want to do a ln+ circular swap with free rebalance.
- It makes very very high cost decisions. My last initial rebalance event was done at ~12673ppm. It should have sane limits about a rebalance economical viability. If it's unsure, it's better to do nothing, and leave the channel unbalanced than to burn that much.

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #108

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
[clboss-balance-unmanage.tar.gz](https://github.com/ZmnSCPxj/clboss/files/8668185/clboss-balance-unmanage.tar.gz) code has not been tested in production, but new unit tests exist and are passing.

@devastgh

This adds a new key to `clboss-unmanage`, `balance`.  To disable rebalancing to and from a specific node, use `lightning-cli clboss-unmanage ${NODEID} balance`.  If you want to also set the LN fees yourself, remember to add it also in the unmanage: `lightning-cli clboss-unmanage ${NODEID} balance,lnfee`.  Same for `close` and `open` unmanagement tags.

**Comment by devastgh** [comment]
Thank you, i'm compiling it now.
What i will do is: add all of my peers into the sqlite database ( Unmanagedmanager_nodes), and set the lnfee,balance tags in Unmanagedmanager_tags for all of them. I haven't been running clboss for a week+ now, and i don't want it to wreak havoc the moment i start it :)



> [clboss-balance-unmanage.tar.gz](https://github.com/ZmnSCPxj/clboss/files/8668185/clboss-balance-unmanage.tar.gz) code has not been tested in production, but new unit tests exist and are passing.
> 
> @devastgh
> 
> This adds a new key to `clboss-unmanage`, `balance`. To disable rebalancing to and from a specific node, use `lightning-cli clboss-unmanage ${NODEID} balance`. If you want to also set the LN fees yourself, remember to add it also in the unmanage: `lightning-cli clboss-unmanage ${NODEID} balance,lnfee`. Same for `close` and `open` unmanagement tags.

**Comment by devastgh** [comment]
Unfortunately this build seems to toally ignore the unmanage flags for me, unless i missed something in the database.
clboss-status correctly lists the flags i set, but both lnfee and balance seems to be ignored.

**Comment by ZmnSCPxj** [comment]
Hmm, strange.  On my own node I see the rebalancers log and they see the unmanaged set.  Hmm.

**Comment by devastgh** [comment]
> Hmm, strange. On my own node I see the rebalancers log and they see the unmanaged set. Hmm.

I think i found something that might be an issue, i started with nodedbid 0 but in my old db it started with 1 in Unmanagedmanager_nodes and Unmanagedmanager_tags .
Weird, cause clboss-status did list everything properly. I'll try to start from 1.

**Comment by ZmnSCPxj** [comment]
Note that the feemodders will still operate and spam the logs, the unmanagement is blocked just before doing `setchannelfee` (and you can set the fees freely and CLBOSS will not change them).

**Comment by devastgh** [comment]
> Note that the feemodders will still operate and spam the logs, the unmanagement is blocked just before doing `setchannelfee` (and you can set the fees freely and CLBOSS will not change them).

Well, tried again, same result. The moment i restart the node with clboss enabled, it will set the fees to all channels, and after a while starts rebalancing. I'll stop trying to insert stuff into the database, and rather write a shell script that does lightning-cli clboss-unmanage for all my channels, and run it after the node starts. 

Edit: It works now 😅
Apparently i missed a space in the database, as 
` "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": "lnfee,balance"` is no good, while
` "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": "balance, lnfee"` is good.

**Comment by ZmnSCPxj** [comment]
Ah, I think what got you is that you are supposed to have separate entries in `UnmanagedManager_tags` rows for `lnfee` and `balance`, but referring to the same `nodedbid`.  The `,` separator only works on the RPC, it is not used on the database.  So what happened is that the `UnmanagedManager` thought there was a tag named literally `balance,lnfee`, not two separate tags `balance` and `lnfee`.

**Comment by devastgh** [comment]
Yep, after checking the db i realized that one tag is one row... Thanks 👍 


> Ah, I think what got you is that you are supposed to have separate entries in `UnmanagedManager_tags` rows for `lnfee` and `balance`, but referring to the same `nodedbid`. The `,` separator only works on the RPC, it is not used on the database. So what happened is that the `UnmanagedManager` thought there was a tag named literally `balance,lnfee`, not two separate tags `balance` and `lnfee`.

**Pull request merged**
