### PR TITLE
Adding Signet option

### PR DESCRIPTION
**Pull request by matthiasdebernardini**
This is referencing the issue #148 adds Signet support by adding the keywords.

It seems to work but I am not sure how to guarantee quality, if there are tests then I would be happy to run them.

As far as I can tell, the only thing missing is being able to test boltz integration 
https://github.com/ZmnSCPxj/clboss/blob/3379983b5a849caa46bb405d07c134e843c248c9/Boss/Mod/BoltzSwapper/Main.cpp#L28

### CODE REVIEW

**Comment by openoms** [comment]
Signet support would be welcome as it is preferred over testnet3.

**Comment by ksedgwic** [comment]
mempool.space thinks signet has 35 lightning nodes while testnet shows 470 and mainnet has 15,487

I'm pretty sure signet would require a patch to min_node_to_process see ZmnSCPxj/clboss@ad49445

I suspect this parameter should be different for each network

**Comment by ksedgwic** [comment]
I added a PR which sets `min_nodes_to_process` to a network specific value: https://github.com/ZmnSCPxj/clboss/pull/173

**Review by vincenzopalazzo — COMMENTED** [review]
OK make sense, if you help to mantaining it.

Also signet is a little bit strange because can be more signet network.

clboss keep a list of nodes (aka seeds) to start connecting with, so this is PR is missing to add it. In addition, we should make sure that this peer should be living enough.

An alternative approach is specify at least one seed as plugin option, this could help with signet, but not sure how the clboss metrics will react with a single node

**Comment by chrisguida** [comment]
Ended up reimplementing this myself before I knew this PR existed https://github.com/ZmnSCPxj/clboss/pull/207

xD

Let's just merge this, it works great for now

**Review by chrisguida — APPROVED** [review]
Works with mutinynet

**Comment by ksedgwic** [comment]
Looks good

**Review by vincenzopalazzo — COMMENTED** [review]
Sorry for being late to the discussion, but I think this PR is missing a list of seed nodes for signet. Or am I missing something?

Additionally, we may want to provide a seed list via a command line option, considering it is unclear how many signet network there are.

**Comment by chrisguida** [comment]
Ah I forgot about seed nodes. You can just connect to the faucet node on mutinynet, you can find the URI on https://faucet.mutinynet.com

**Comment by ksedgwic** [comment]
There is another PR for updating the mainnet seed nodes.  The CLBOSS support isn't very good on any network.  I generally make a few manual seed connections and bootstrap gossip that way ...

Maybe we should make a DNS based thing so at least the nodes aren't compiled in ...

**Comment by ksedgwic** [comment]
to clarify, I only make initial gossip connections manually, everything else works automatically

**Pull request merged**
