### PR TITLE
Fix build issue w/ htlc_accepted_cont signature

### LINKED ISSUE #166: Build Issue w/ CommandId
Build fails:
```
make[2]: Entering directory '/usr/local/src/clboss'
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -std=gnu++11 -DHAVE_CONFIG_H -I.  -I./external/basicsecure/ -I./external/bitcoin-ripemd160/ -I./external/bitcoin-sha256/ -I./external/secp256k1/include/ -I./external/jsmn  -Wall -Werror -pthread    -Wno-noexcept-type  -O2 -MT Boss/Mod/libclboss_la-JitRebalancer.lo -MD -MP -MF Boss/Mod/.deps/libclboss_la-JitRebalancer.Tpo -c -o Boss/Mod/libclboss_la-JitRebalancer.lo `test -f 'Boss/Mod/JitRebalancer.cpp' || echo './'`Boss/Mod/JitRebalancer.cpp
libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./external/basicsecure/ -I./external/bitcoin-ripemd160/ -I./external/bitcoin-sha256/ -I./external/secp256k1/include/ -I./external/jsmn -Wall -Werror -pthread -Wno-noexcept-type -O2 -MT Boss/Mod/libclboss_la-JitRebalancer.lo -MD -MP -MF Boss/Mod/.deps/libclboss_la-JitRebalancer.Tpo -c Boss/Mod/JitRebalancer.cpp -o Boss/Mod/libclboss_la-JitRebalancer.o
Boss/Mod/JitRebalancer.cpp: In lambda function:
Boss/Mod/JitRebalancer.cpp:137:14: error: cannot convert ‘const CommandId’ {aka ‘const Util::Either<long unsigned int, std::__cxx11::basic_string<char> >’} to ‘uint64_t’ {aka ‘long unsigned int’}
  137 |        , req.id
      |          ~~~~^~
      |              |
      |              const CommandId {aka const Util::Either<long unsigned int, std::__cxx11::basic_string<char> >}
Boss/Mod/JitRebalancer.cpp:144:22: note:   initializing argument 2 of ‘Ev::Io<bool> Boss::Mod::JitRebalancer::Impl::htlc_accepted_cont(const Ln::NodeId&, uint64_t, Ln::Amount)’
  144 |      , std::uint64_t id
      |        ~~~~~~~~~~~~~~^~
Boss/Mod/JitRebalancer.cpp: In lambda function:
Boss/Mod/JitRebalancer.cpp:157:23: error: invalid initialization of reference of type ‘const CommandId&’ {aka ‘const Util::Either<long unsigned int, std::__cxx11::basic_string<char> >&’} from expression of type ‘const uint64_t’ {aka ‘const long unsigned int’}
  157 |       , stringify_cid(id).c_str()
      |                       ^~
Boss/Mod/JitRebalancer.cpp:72:48: note: in passing argument 1 of ‘std::string {anonymous}::stringify_cid(const CommandId&)’
   72 | std::string stringify_cid(Ln::CommandId const& id) {
      |                           ~~~~~~~~~~~~~~~~~~~~~^~
Boss/Mod/JitRebalancer.cpp:163:58: error: cannot convert ‘const uint64_t’ {aka ‘const long unsigned int’} to ‘Ln::CommandId’ {aka ‘Util::Either<long unsigned int, std::__cxx11::basic_string<char> >’}
  163 |    return Boss::concurrent( check_and_move(node, amount, id)
      |                                                          ^~
      |                                                          |
      |                                                          const uint64_t {aka const long unsigned int}
Boss/Mod/JitRebalancer.cpp:196:25: note:   initializing argument 3 of ‘Ev::Io<void> Boss::Mod::JitRebalancer::Impl::check_and_move(const Ln::NodeId&, Ln::Amount, Ln::CommandId)’
  196 |         , Ln::CommandId id
      |           ~~~~~~~~~~~~~~^~
Boss/Mod/JitRebalancer.cpp: In member function ‘Ev::Io<bool> Boss::Mod::JitRebalancer::Impl::htlc_accepted_cont(const Ln::NodeId&, uint64_t, Ln::Amount)’:
Boss/Mod/JitRebalancer.cpp:167:4: error: no matching function for call to ‘Ev::Io<const std::set<Ln::NodeId>*>::then(Boss::Mod::JitRebalancer::Impl::htlc_accepted_cont(const Ln::NodeId&, uint64_t, Ln::Amount)::<lambda(const std::set<Ln::NodeId>*)>)’
  167 |   });
      |    ^
In file included from ./Boss/ModG/ReqResp.hpp:7,
                 from ./Boss/ModG/RebalanceUnmanagerProxy.hpp:4,
                 from Boss/Mod/JitRebalancer.cpp:2:
./Ev/Io.hpp:95:2: note: candidate: ‘template<class f> Ev::Io<typename Ev::Detail::IoInner<typename std::result_of<f(a)>::type>::type> Ev::Io<a>::then(f) && [with f = f; a = const std::set<Ln::NodeId>*]’
   95 |  then(f func)&& {
      |  ^~~~
./Ev/Io.hpp:95:2: note:   template argument deduction/substitution failed:
./Ev/Io.hpp: In substitution of ‘template<class f> Ev::Io<typename Ev::Detail::IoInner<typename std::result_of<f(const std::set<Ln::NodeId>*)>::type>::type> Ev::Io<const std::set<Ln::NodeId>*>::then<f>(f) && [with f = Boss::Mod::JitRebalancer::Impl::htlc_accepted_cont(const Ln::NodeId&, uint64_t, Ln::Amount)::<lambda(const std::set<Ln::NodeId>*)>]’:
Boss/Mod/JitRebalancer.cpp:167:4:   required from here
./Ev/Io.hpp:95:2: error: no type named ‘type’ in ‘class std::result_of<Boss::Mod::JitRebalancer::Impl::htlc_accepted_cont(const Ln::NodeId&, uint64_t, Ln::Amount)::<lambda(const std::set<Ln::NodeId>*)>(const std::set<Ln::NodeId>*)>’
make[2]: *** [Makefile:4606: Boss/Mod/libclboss_la-JitRebalancer.lo] Error 1
```

CLBOSS version
```
git rev-parse --short HEAD
b2def4c
```
Compiler version:
```
g++ --version
g++ (Debian 10.2.1-6) 10.2.1 20210110
```
OS version:
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### PR DESCRIPTION
**Pull request by ksedgwic**
Fixes #166

### CODE REVIEW

**Comment by ksedgwic** [comment]
I rebased this on top of @vincenzopalazzo 's (merged) #168 so we can see if the CI passes

**Comment by ksedgwic** [comment]
Seeing many of the following error in CI:
```
2023-08-17T23:18:28.1513627Z ../../../../external/secp256k1/src/bench_verify.c: In function ‘bench_verify_openssl’:
2023-08-17T23:18:28.1529977Z ../../../../external/secp256k1/src/bench_verify.c:63:13: warning: ‘EC_KEY_new’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
2023-08-17T23:18:28.1537720Z    63 |             EC_KEY *pkey = EC_KEY_new();
2023-08-17T23:18:28.1538157Z       |             ^~~~~~
2023-08-17T23:18:28.1541268Z In file included from /nix/store/1i02aisfli8788mlgfm56bykd1pix0sc-openssl-3.0.9-dev/include/openssl/ecdsa.h:10,
2023-08-17T23:18:28.1542121Z                  from ../../../../external/secp256k1/src/bench_verify.c:16:
2023-08-17T23:18:28.1542748Z /nix/store/1i02aisfli8788mlgfm56bykd1pix0sc-openssl-3.0.9-dev/include/openssl/ec.h:968:31: note: declared here
2023-08-17T23:18:28.1543258Z   968 | OSSL_DEPRECATEDIN_3_0 EC_KEY *EC_KEY_new(void);
2023-08-17T23:18:28.1543600Z       |                               ^~~~~~~~~~
```

I think this is seen in CI but not on my local machine because the CI env has a newer `openssl`.

Added a `-Wno-deprecated-declarations` in a couple places in the secp256k1 build.

Is there a cleaner way to get around this warning/error?

[...later...]

The `external/secp256k1` tests are still failing, but not on my local machines

**Comment by vincenzopalazzo** [comment]
Sorry for delay here.

If I ran the code with nix on my machine the result is the same

```
============================================================================
make[4]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/basicsecure'
make[3]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/basicsecure'
make[2]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/basicsecure'
Making check in external/bitcoin-ripemd160
make[2]: Entering directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/bitcoin-ripemd160'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/bitcoin-ripemd160'
Making check in external/bitcoin-sha256
make[2]: Entering directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/bitcoin-sha256'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/bitcoin-sha256'
Making check in external/secp256k1/
make[2]: Entering directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/secp256k1'
make  check-TESTS
make[3]: Entering directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/secp256k1'
make[4]: Entering directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/secp256k1'
PASS: exhaustive_tests
../../../../external/secp256k1/build-aux/test-driver: line 112: 929773 Aborted                 "$@" >> "$log_file" 2>&1
FAIL: tests
============================================================================
Testsuite summary for libsecp256k1 0.1
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
make[4]: *** [Makefile:1209: test-suite.log] Error 1
make[4]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/secp256k1'
make[3]: *** [Makefile:1317: check-TESTS] Error 2
make[3]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/secp256k1'
make[2]: *** [Makefile:1535: check-am] Error 2
make[2]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub/external/secp256k1'
make[1]: *** [Makefile:5474: check-recursive] Error 1
make[1]: Leaving directory '/home/vincent/Github/clboss/clboss-0.13A/_build/sub'
make: *** [Makefile:6325: distcheck] Error 1
```

Now I will try to debug it a little bit

**Comment by ksedgwic** [comment]
This is superseded by #169

**Pull request closed without merging**
