### PR TITLE
minor post release improvment

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
This is just changing the version number and put there some tar hash to add the tar file as release file

### CODE REVIEW

**Comment by chrisguida** [comment]
I can verify that `make dist` produces the same hash of the source tarball on my machine:

```
make -j$(nproc) dist | grep --exclude="tardir=*" " *.tar.gz"
tardir=clboss-0.13 && tar --format=ustar --mtime='1970-01-01 00:00Z' --sort=name --owner=0 --group=0 --numeric-owner -chf - "$tardir" | eval GZIP= gzip --best -c >clboss-0.13.tar.gz
88836e6ff47dbf7fbdfa2dcaf8b4348cef031eeda830e2410a49a5b44d57d358  clboss-0.13.tar.gz
```

however, this same hash is produced whether or not you actually execute the build, which indicates that the hash is only committing to the contents of the source tarball.

I don't understand what the point of this is, since `git` already allows you to reproduce the source on any machine.

**Comment by vincenzopalazzo** [comment]
```
88836e6ff47dbf7fbdfa2dcaf8b4348cef031eeda830e2410a49a5b44d57d358  clboss-0.13.tar.gz
make[1]: Leaving directory '/workspace/clboss'
if test -d "clboss-0.13"; then find "clboss-0.13" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "clboss-0.13" || { sleep 5 && rm -rf "clboss-0.13"; }; else :; fi
[nix-develop]$ 
```

**Comment by chrisguida** [comment]
Ok, @vincenzopalazzo points out that the source tarball needs to be reproducible for people who don't use git. It's possible that `nix` itself may do this if it downloads the tarball from somewhere other than a git repo, so I guess there's a point to all of this after all :)

It's just not a bit-for-bit identical binary "reproducible build". Just "reproducible source".

**Comment by chrisguida** [comment]
@vincenzopalazzo on the latest commit (ab5135bb3b5370f3a6ded0a6bd7058b6b5118451) i get:

```
make -j$(nproc) dist | grep --exclude="tardir=*" " *.tar.gz"
tardir=clboss-0.13 && tar --format=ustar --mtime='1970-01-01 00:00Z' --sort=name --owner=0 --group=0 --numeric-owner -chf - "$tardir" | eval GZIP= gzip --best -c >clboss-0.13.tar.gz
40f41f8d0efc131b08beb2cd428638f6f2ee11facac1975208b978472e7dae27  clboss-0.13.tar.gz
```

Can you verify that this is correct?

**Comment by ksedgwic** [comment]
@chrisguida @vincenzopalazzo is this ready or close to ready?

**Comment by ksedgwic** [comment]
@chrisguida @vincenzopalazzo looking to do a point release here for the "no channels" fix (#189)

Should this go in too?  Is it ready?

**Comment by chrisguida** [comment]
I'm out of commission for the next week or so, sorry!

**Comment by ksedgwic** [comment]
Fixes #181

**Pull request merged**
